### PR TITLE
add notifications

### PR DESCRIPTION
**Pull request by treeshateorcs**

### CODE REVIEW

**Comment by InputUsername** [comment]
What's the use case for this? Does your music player have an option to show notifications?

**Comment by treeshateorcs** [comment]
these are shown using the standard linux notification system called notifyd. you can see what it does yourself if you issue 
$ notify-send test

my player does not show them (I use ncspot and cmus). they are only a few lines and completely optional, i think it won't hurt if they are there

**Comment by InputUsername** [comment]
I've personally only used the official Spotify client which does show notifications, but you're right, it adding it won't hurt. I'll merge this PR after #4 because it contains some commits from #4.

**Comment by treeshateorcs** [comment]
maybe reject #4 and merge this? i will make requested changes on this one

**Comment by InputUsername** [comment]
I would prefer keeping changes related to #4 in that PR. Maybe you can rebase this one against `master` (in this repo) so only the notification part will be added?

**Comment by treeshateorcs** [comment]
sorry i'm a git noob :( i've updated #4

**Comment by InputUsername** [comment]
No worries. I will merge #4 first then, that shouldn't cause problems.

**Pull request merged**
